project:
  type: website
  output-dir: docs

website:
  title: "gerverhlopez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Technical
        href: sri.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

